// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mystats-server/internal/ent/batterrecord"
	"mystats-server/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BatterRecordDelete is the builder for deleting a BatterRecord entity.
type BatterRecordDelete struct {
	config
	hooks    []Hook
	mutation *BatterRecordMutation
}

// Where appends a list predicates to the BatterRecordDelete builder.
func (brd *BatterRecordDelete) Where(ps ...predicate.BatterRecord) *BatterRecordDelete {
	brd.mutation.Where(ps...)
	return brd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (brd *BatterRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, brd.sqlExec, brd.mutation, brd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (brd *BatterRecordDelete) ExecX(ctx context.Context) int {
	n, err := brd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (brd *BatterRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(batterrecord.Table, sqlgraph.NewFieldSpec(batterrecord.FieldID, field.TypeInt))
	if ps := brd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, brd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	brd.mutation.done = true
	return affected, err
}

// BatterRecordDeleteOne is the builder for deleting a single BatterRecord entity.
type BatterRecordDeleteOne struct {
	brd *BatterRecordDelete
}

// Where appends a list predicates to the BatterRecordDelete builder.
func (brdo *BatterRecordDeleteOne) Where(ps ...predicate.BatterRecord) *BatterRecordDeleteOne {
	brdo.brd.mutation.Where(ps...)
	return brdo
}

// Exec executes the deletion query.
func (brdo *BatterRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := brdo.brd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{batterrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (brdo *BatterRecordDeleteOne) ExecX(ctx context.Context) {
	if err := brdo.Exec(ctx); err != nil {
		panic(err)
	}
}
