// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"mystats-server/internal/ent/batterrecord"
	"mystats-server/internal/ent/game"
	"mystats-server/internal/ent/predicate"
	"mystats-server/internal/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BatterRecordQuery is the builder for querying BatterRecord entities.
type BatterRecordQuery struct {
	config
	ctx        *QueryContext
	order      []batterrecord.OrderOption
	inters     []Interceptor
	predicates []predicate.BatterRecord
	withUser   *UserQuery
	withGame   *GameQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BatterRecordQuery builder.
func (brq *BatterRecordQuery) Where(ps ...predicate.BatterRecord) *BatterRecordQuery {
	brq.predicates = append(brq.predicates, ps...)
	return brq
}

// Limit the number of records to be returned by this query.
func (brq *BatterRecordQuery) Limit(limit int) *BatterRecordQuery {
	brq.ctx.Limit = &limit
	return brq
}

// Offset to start from.
func (brq *BatterRecordQuery) Offset(offset int) *BatterRecordQuery {
	brq.ctx.Offset = &offset
	return brq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (brq *BatterRecordQuery) Unique(unique bool) *BatterRecordQuery {
	brq.ctx.Unique = &unique
	return brq
}

// Order specifies how the records should be ordered.
func (brq *BatterRecordQuery) Order(o ...batterrecord.OrderOption) *BatterRecordQuery {
	brq.order = append(brq.order, o...)
	return brq
}

// QueryUser chains the current query on the "user" edge.
func (brq *BatterRecordQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: brq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := brq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := brq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(batterrecord.Table, batterrecord.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, batterrecord.UserTable, batterrecord.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(brq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGame chains the current query on the "game" edge.
func (brq *BatterRecordQuery) QueryGame() *GameQuery {
	query := (&GameClient{config: brq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := brq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := brq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(batterrecord.Table, batterrecord.FieldID, selector),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, batterrecord.GameTable, batterrecord.GameColumn),
		)
		fromU = sqlgraph.SetNeighbors(brq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BatterRecord entity from the query.
// Returns a *NotFoundError when no BatterRecord was found.
func (brq *BatterRecordQuery) First(ctx context.Context) (*BatterRecord, error) {
	nodes, err := brq.Limit(1).All(setContextOp(ctx, brq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{batterrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (brq *BatterRecordQuery) FirstX(ctx context.Context) *BatterRecord {
	node, err := brq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BatterRecord ID from the query.
// Returns a *NotFoundError when no BatterRecord ID was found.
func (brq *BatterRecordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = brq.Limit(1).IDs(setContextOp(ctx, brq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{batterrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (brq *BatterRecordQuery) FirstIDX(ctx context.Context) int {
	id, err := brq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BatterRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BatterRecord entity is found.
// Returns a *NotFoundError when no BatterRecord entities are found.
func (brq *BatterRecordQuery) Only(ctx context.Context) (*BatterRecord, error) {
	nodes, err := brq.Limit(2).All(setContextOp(ctx, brq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{batterrecord.Label}
	default:
		return nil, &NotSingularError{batterrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (brq *BatterRecordQuery) OnlyX(ctx context.Context) *BatterRecord {
	node, err := brq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BatterRecord ID in the query.
// Returns a *NotSingularError when more than one BatterRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (brq *BatterRecordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = brq.Limit(2).IDs(setContextOp(ctx, brq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{batterrecord.Label}
	default:
		err = &NotSingularError{batterrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (brq *BatterRecordQuery) OnlyIDX(ctx context.Context) int {
	id, err := brq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BatterRecords.
func (brq *BatterRecordQuery) All(ctx context.Context) ([]*BatterRecord, error) {
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryAll)
	if err := brq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BatterRecord, *BatterRecordQuery]()
	return withInterceptors[[]*BatterRecord](ctx, brq, qr, brq.inters)
}

// AllX is like All, but panics if an error occurs.
func (brq *BatterRecordQuery) AllX(ctx context.Context) []*BatterRecord {
	nodes, err := brq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BatterRecord IDs.
func (brq *BatterRecordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if brq.ctx.Unique == nil && brq.path != nil {
		brq.Unique(true)
	}
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryIDs)
	if err = brq.Select(batterrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (brq *BatterRecordQuery) IDsX(ctx context.Context) []int {
	ids, err := brq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (brq *BatterRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryCount)
	if err := brq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, brq, querierCount[*BatterRecordQuery](), brq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (brq *BatterRecordQuery) CountX(ctx context.Context) int {
	count, err := brq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (brq *BatterRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, brq.ctx, ent.OpQueryExist)
	switch _, err := brq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (brq *BatterRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := brq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BatterRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (brq *BatterRecordQuery) Clone() *BatterRecordQuery {
	if brq == nil {
		return nil
	}
	return &BatterRecordQuery{
		config:     brq.config,
		ctx:        brq.ctx.Clone(),
		order:      append([]batterrecord.OrderOption{}, brq.order...),
		inters:     append([]Interceptor{}, brq.inters...),
		predicates: append([]predicate.BatterRecord{}, brq.predicates...),
		withUser:   brq.withUser.Clone(),
		withGame:   brq.withGame.Clone(),
		// clone intermediate query.
		sql:  brq.sql.Clone(),
		path: brq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (brq *BatterRecordQuery) WithUser(opts ...func(*UserQuery)) *BatterRecordQuery {
	query := (&UserClient{config: brq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	brq.withUser = query
	return brq
}

// WithGame tells the query-builder to eager-load the nodes that are connected to
// the "game" edge. The optional arguments are used to configure the query builder of the edge.
func (brq *BatterRecordQuery) WithGame(opts ...func(*GameQuery)) *BatterRecordQuery {
	query := (&GameClient{config: brq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	brq.withGame = query
	return brq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Games int `json:"games,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BatterRecord.Query().
//		GroupBy(batterrecord.FieldGames).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (brq *BatterRecordQuery) GroupBy(field string, fields ...string) *BatterRecordGroupBy {
	brq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BatterRecordGroupBy{build: brq}
	grbuild.flds = &brq.ctx.Fields
	grbuild.label = batterrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Games int `json:"games,omitempty"`
//	}
//
//	client.BatterRecord.Query().
//		Select(batterrecord.FieldGames).
//		Scan(ctx, &v)
func (brq *BatterRecordQuery) Select(fields ...string) *BatterRecordSelect {
	brq.ctx.Fields = append(brq.ctx.Fields, fields...)
	sbuild := &BatterRecordSelect{BatterRecordQuery: brq}
	sbuild.label = batterrecord.Label
	sbuild.flds, sbuild.scan = &brq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BatterRecordSelect configured with the given aggregations.
func (brq *BatterRecordQuery) Aggregate(fns ...AggregateFunc) *BatterRecordSelect {
	return brq.Select().Aggregate(fns...)
}

func (brq *BatterRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range brq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, brq); err != nil {
				return err
			}
		}
	}
	for _, f := range brq.ctx.Fields {
		if !batterrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if brq.path != nil {
		prev, err := brq.path(ctx)
		if err != nil {
			return err
		}
		brq.sql = prev
	}
	return nil
}

func (brq *BatterRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BatterRecord, error) {
	var (
		nodes       = []*BatterRecord{}
		withFKs     = brq.withFKs
		_spec       = brq.querySpec()
		loadedTypes = [2]bool{
			brq.withUser != nil,
			brq.withGame != nil,
		}
	)
	if brq.withUser != nil || brq.withGame != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, batterrecord.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BatterRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BatterRecord{config: brq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, brq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := brq.withUser; query != nil {
		if err := brq.loadUser(ctx, query, nodes, nil,
			func(n *BatterRecord, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := brq.withGame; query != nil {
		if err := brq.loadGame(ctx, query, nodes, nil,
			func(n *BatterRecord, e *Game) { n.Edges.Game = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (brq *BatterRecordQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*BatterRecord, init func(*BatterRecord), assign func(*BatterRecord, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BatterRecord)
	for i := range nodes {
		if nodes[i].user_batting_records == nil {
			continue
		}
		fk := *nodes[i].user_batting_records
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_batting_records" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (brq *BatterRecordQuery) loadGame(ctx context.Context, query *GameQuery, nodes []*BatterRecord, init func(*BatterRecord), assign func(*BatterRecord, *Game)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BatterRecord)
	for i := range nodes {
		if nodes[i].game_batting_records == nil {
			continue
		}
		fk := *nodes[i].game_batting_records
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(game.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "game_batting_records" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (brq *BatterRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := brq.querySpec()
	_spec.Node.Columns = brq.ctx.Fields
	if len(brq.ctx.Fields) > 0 {
		_spec.Unique = brq.ctx.Unique != nil && *brq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, brq.driver, _spec)
}

func (brq *BatterRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(batterrecord.Table, batterrecord.Columns, sqlgraph.NewFieldSpec(batterrecord.FieldID, field.TypeInt))
	_spec.From = brq.sql
	if unique := brq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if brq.path != nil {
		_spec.Unique = true
	}
	if fields := brq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, batterrecord.FieldID)
		for i := range fields {
			if fields[i] != batterrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := brq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := brq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := brq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := brq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (brq *BatterRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(brq.driver.Dialect())
	t1 := builder.Table(batterrecord.Table)
	columns := brq.ctx.Fields
	if len(columns) == 0 {
		columns = batterrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if brq.sql != nil {
		selector = brq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if brq.ctx.Unique != nil && *brq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range brq.predicates {
		p(selector)
	}
	for _, p := range brq.order {
		p(selector)
	}
	if offset := brq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := brq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BatterRecordGroupBy is the group-by builder for BatterRecord entities.
type BatterRecordGroupBy struct {
	selector
	build *BatterRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (brgb *BatterRecordGroupBy) Aggregate(fns ...AggregateFunc) *BatterRecordGroupBy {
	brgb.fns = append(brgb.fns, fns...)
	return brgb
}

// Scan applies the selector query and scans the result into the given value.
func (brgb *BatterRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, brgb.build.ctx, ent.OpQueryGroupBy)
	if err := brgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BatterRecordQuery, *BatterRecordGroupBy](ctx, brgb.build, brgb, brgb.build.inters, v)
}

func (brgb *BatterRecordGroupBy) sqlScan(ctx context.Context, root *BatterRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(brgb.fns))
	for _, fn := range brgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*brgb.flds)+len(brgb.fns))
		for _, f := range *brgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*brgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := brgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BatterRecordSelect is the builder for selecting fields of BatterRecord entities.
type BatterRecordSelect struct {
	*BatterRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (brs *BatterRecordSelect) Aggregate(fns ...AggregateFunc) *BatterRecordSelect {
	brs.fns = append(brs.fns, fns...)
	return brs
}

// Scan applies the selector query and scans the result into the given value.
func (brs *BatterRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, brs.ctx, ent.OpQuerySelect)
	if err := brs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BatterRecordQuery, *BatterRecordSelect](ctx, brs.BatterRecordQuery, brs, brs.inters, v)
}

func (brs *BatterRecordSelect) sqlScan(ctx context.Context, root *BatterRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(brs.fns))
	for _, fn := range brs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*brs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := brs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
