// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"mystats-server/internal/ent/game"
	"mystats-server/internal/ent/pitcherrecord"
	"mystats-server/internal/ent/predicate"
	"mystats-server/internal/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PitcherRecordQuery is the builder for querying PitcherRecord entities.
type PitcherRecordQuery struct {
	config
	ctx        *QueryContext
	order      []pitcherrecord.OrderOption
	inters     []Interceptor
	predicates []predicate.PitcherRecord
	withUser   *UserQuery
	withGame   *GameQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PitcherRecordQuery builder.
func (prq *PitcherRecordQuery) Where(ps ...predicate.PitcherRecord) *PitcherRecordQuery {
	prq.predicates = append(prq.predicates, ps...)
	return prq
}

// Limit the number of records to be returned by this query.
func (prq *PitcherRecordQuery) Limit(limit int) *PitcherRecordQuery {
	prq.ctx.Limit = &limit
	return prq
}

// Offset to start from.
func (prq *PitcherRecordQuery) Offset(offset int) *PitcherRecordQuery {
	prq.ctx.Offset = &offset
	return prq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (prq *PitcherRecordQuery) Unique(unique bool) *PitcherRecordQuery {
	prq.ctx.Unique = &unique
	return prq
}

// Order specifies how the records should be ordered.
func (prq *PitcherRecordQuery) Order(o ...pitcherrecord.OrderOption) *PitcherRecordQuery {
	prq.order = append(prq.order, o...)
	return prq
}

// QueryUser chains the current query on the "user" edge.
func (prq *PitcherRecordQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pitcherrecord.Table, pitcherrecord.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pitcherrecord.UserTable, pitcherrecord.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGame chains the current query on the "game" edge.
func (prq *PitcherRecordQuery) QueryGame() *GameQuery {
	query := (&GameClient{config: prq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := prq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pitcherrecord.Table, pitcherrecord.FieldID, selector),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pitcherrecord.GameTable, pitcherrecord.GameColumn),
		)
		fromU = sqlgraph.SetNeighbors(prq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PitcherRecord entity from the query.
// Returns a *NotFoundError when no PitcherRecord was found.
func (prq *PitcherRecordQuery) First(ctx context.Context) (*PitcherRecord, error) {
	nodes, err := prq.Limit(1).All(setContextOp(ctx, prq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pitcherrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (prq *PitcherRecordQuery) FirstX(ctx context.Context) *PitcherRecord {
	node, err := prq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PitcherRecord ID from the query.
// Returns a *NotFoundError when no PitcherRecord ID was found.
func (prq *PitcherRecordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = prq.Limit(1).IDs(setContextOp(ctx, prq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pitcherrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (prq *PitcherRecordQuery) FirstIDX(ctx context.Context) int {
	id, err := prq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PitcherRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PitcherRecord entity is found.
// Returns a *NotFoundError when no PitcherRecord entities are found.
func (prq *PitcherRecordQuery) Only(ctx context.Context) (*PitcherRecord, error) {
	nodes, err := prq.Limit(2).All(setContextOp(ctx, prq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pitcherrecord.Label}
	default:
		return nil, &NotSingularError{pitcherrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (prq *PitcherRecordQuery) OnlyX(ctx context.Context) *PitcherRecord {
	node, err := prq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PitcherRecord ID in the query.
// Returns a *NotSingularError when more than one PitcherRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (prq *PitcherRecordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = prq.Limit(2).IDs(setContextOp(ctx, prq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pitcherrecord.Label}
	default:
		err = &NotSingularError{pitcherrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (prq *PitcherRecordQuery) OnlyIDX(ctx context.Context) int {
	id, err := prq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PitcherRecords.
func (prq *PitcherRecordQuery) All(ctx context.Context) ([]*PitcherRecord, error) {
	ctx = setContextOp(ctx, prq.ctx, ent.OpQueryAll)
	if err := prq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PitcherRecord, *PitcherRecordQuery]()
	return withInterceptors[[]*PitcherRecord](ctx, prq, qr, prq.inters)
}

// AllX is like All, but panics if an error occurs.
func (prq *PitcherRecordQuery) AllX(ctx context.Context) []*PitcherRecord {
	nodes, err := prq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PitcherRecord IDs.
func (prq *PitcherRecordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if prq.ctx.Unique == nil && prq.path != nil {
		prq.Unique(true)
	}
	ctx = setContextOp(ctx, prq.ctx, ent.OpQueryIDs)
	if err = prq.Select(pitcherrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (prq *PitcherRecordQuery) IDsX(ctx context.Context) []int {
	ids, err := prq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (prq *PitcherRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, prq.ctx, ent.OpQueryCount)
	if err := prq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, prq, querierCount[*PitcherRecordQuery](), prq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (prq *PitcherRecordQuery) CountX(ctx context.Context) int {
	count, err := prq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (prq *PitcherRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, prq.ctx, ent.OpQueryExist)
	switch _, err := prq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (prq *PitcherRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := prq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PitcherRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (prq *PitcherRecordQuery) Clone() *PitcherRecordQuery {
	if prq == nil {
		return nil
	}
	return &PitcherRecordQuery{
		config:     prq.config,
		ctx:        prq.ctx.Clone(),
		order:      append([]pitcherrecord.OrderOption{}, prq.order...),
		inters:     append([]Interceptor{}, prq.inters...),
		predicates: append([]predicate.PitcherRecord{}, prq.predicates...),
		withUser:   prq.withUser.Clone(),
		withGame:   prq.withGame.Clone(),
		// clone intermediate query.
		sql:  prq.sql.Clone(),
		path: prq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PitcherRecordQuery) WithUser(opts ...func(*UserQuery)) *PitcherRecordQuery {
	query := (&UserClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withUser = query
	return prq
}

// WithGame tells the query-builder to eager-load the nodes that are connected to
// the "game" edge. The optional arguments are used to configure the query builder of the edge.
func (prq *PitcherRecordQuery) WithGame(opts ...func(*GameQuery)) *PitcherRecordQuery {
	query := (&GameClient{config: prq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	prq.withGame = query
	return prq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Games int `json:"games,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PitcherRecord.Query().
//		GroupBy(pitcherrecord.FieldGames).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (prq *PitcherRecordQuery) GroupBy(field string, fields ...string) *PitcherRecordGroupBy {
	prq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PitcherRecordGroupBy{build: prq}
	grbuild.flds = &prq.ctx.Fields
	grbuild.label = pitcherrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Games int `json:"games,omitempty"`
//	}
//
//	client.PitcherRecord.Query().
//		Select(pitcherrecord.FieldGames).
//		Scan(ctx, &v)
func (prq *PitcherRecordQuery) Select(fields ...string) *PitcherRecordSelect {
	prq.ctx.Fields = append(prq.ctx.Fields, fields...)
	sbuild := &PitcherRecordSelect{PitcherRecordQuery: prq}
	sbuild.label = pitcherrecord.Label
	sbuild.flds, sbuild.scan = &prq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PitcherRecordSelect configured with the given aggregations.
func (prq *PitcherRecordQuery) Aggregate(fns ...AggregateFunc) *PitcherRecordSelect {
	return prq.Select().Aggregate(fns...)
}

func (prq *PitcherRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range prq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, prq); err != nil {
				return err
			}
		}
	}
	for _, f := range prq.ctx.Fields {
		if !pitcherrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if prq.path != nil {
		prev, err := prq.path(ctx)
		if err != nil {
			return err
		}
		prq.sql = prev
	}
	return nil
}

func (prq *PitcherRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PitcherRecord, error) {
	var (
		nodes       = []*PitcherRecord{}
		withFKs     = prq.withFKs
		_spec       = prq.querySpec()
		loadedTypes = [2]bool{
			prq.withUser != nil,
			prq.withGame != nil,
		}
	)
	if prq.withUser != nil || prq.withGame != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, pitcherrecord.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PitcherRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PitcherRecord{config: prq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, prq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := prq.withUser; query != nil {
		if err := prq.loadUser(ctx, query, nodes, nil,
			func(n *PitcherRecord, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := prq.withGame; query != nil {
		if err := prq.loadGame(ctx, query, nodes, nil,
			func(n *PitcherRecord, e *Game) { n.Edges.Game = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (prq *PitcherRecordQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*PitcherRecord, init func(*PitcherRecord), assign func(*PitcherRecord, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PitcherRecord)
	for i := range nodes {
		if nodes[i].user_pitching_records == nil {
			continue
		}
		fk := *nodes[i].user_pitching_records
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_pitching_records" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (prq *PitcherRecordQuery) loadGame(ctx context.Context, query *GameQuery, nodes []*PitcherRecord, init func(*PitcherRecord), assign func(*PitcherRecord, *Game)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PitcherRecord)
	for i := range nodes {
		if nodes[i].game_pitching_records == nil {
			continue
		}
		fk := *nodes[i].game_pitching_records
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(game.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "game_pitching_records" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (prq *PitcherRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := prq.querySpec()
	_spec.Node.Columns = prq.ctx.Fields
	if len(prq.ctx.Fields) > 0 {
		_spec.Unique = prq.ctx.Unique != nil && *prq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, prq.driver, _spec)
}

func (prq *PitcherRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pitcherrecord.Table, pitcherrecord.Columns, sqlgraph.NewFieldSpec(pitcherrecord.FieldID, field.TypeInt))
	_spec.From = prq.sql
	if unique := prq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if prq.path != nil {
		_spec.Unique = true
	}
	if fields := prq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pitcherrecord.FieldID)
		for i := range fields {
			if fields[i] != pitcherrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := prq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := prq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := prq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := prq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (prq *PitcherRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(prq.driver.Dialect())
	t1 := builder.Table(pitcherrecord.Table)
	columns := prq.ctx.Fields
	if len(columns) == 0 {
		columns = pitcherrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if prq.sql != nil {
		selector = prq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if prq.ctx.Unique != nil && *prq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range prq.predicates {
		p(selector)
	}
	for _, p := range prq.order {
		p(selector)
	}
	if offset := prq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := prq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PitcherRecordGroupBy is the group-by builder for PitcherRecord entities.
type PitcherRecordGroupBy struct {
	selector
	build *PitcherRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (prgb *PitcherRecordGroupBy) Aggregate(fns ...AggregateFunc) *PitcherRecordGroupBy {
	prgb.fns = append(prgb.fns, fns...)
	return prgb
}

// Scan applies the selector query and scans the result into the given value.
func (prgb *PitcherRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prgb.build.ctx, ent.OpQueryGroupBy)
	if err := prgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PitcherRecordQuery, *PitcherRecordGroupBy](ctx, prgb.build, prgb, prgb.build.inters, v)
}

func (prgb *PitcherRecordGroupBy) sqlScan(ctx context.Context, root *PitcherRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(prgb.fns))
	for _, fn := range prgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*prgb.flds)+len(prgb.fns))
		for _, f := range *prgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*prgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PitcherRecordSelect is the builder for selecting fields of PitcherRecord entities.
type PitcherRecordSelect struct {
	*PitcherRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (prs *PitcherRecordSelect) Aggregate(fns ...AggregateFunc) *PitcherRecordSelect {
	prs.fns = append(prs.fns, fns...)
	return prs
}

// Scan applies the selector query and scans the result into the given value.
func (prs *PitcherRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, prs.ctx, ent.OpQuerySelect)
	if err := prs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PitcherRecordQuery, *PitcherRecordSelect](ctx, prs.PitcherRecordQuery, prs, prs.inters, v)
}

func (prs *PitcherRecordSelect) sqlScan(ctx context.Context, root *PitcherRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(prs.fns))
	for _, fn := range prs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*prs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
