// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mystats-server/internal/ent/pitcherrecord"
	"mystats-server/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PitcherRecordDelete is the builder for deleting a PitcherRecord entity.
type PitcherRecordDelete struct {
	config
	hooks    []Hook
	mutation *PitcherRecordMutation
}

// Where appends a list predicates to the PitcherRecordDelete builder.
func (prd *PitcherRecordDelete) Where(ps ...predicate.PitcherRecord) *PitcherRecordDelete {
	prd.mutation.Where(ps...)
	return prd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (prd *PitcherRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, prd.sqlExec, prd.mutation, prd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (prd *PitcherRecordDelete) ExecX(ctx context.Context) int {
	n, err := prd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (prd *PitcherRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pitcherrecord.Table, sqlgraph.NewFieldSpec(pitcherrecord.FieldID, field.TypeInt))
	if ps := prd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, prd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	prd.mutation.done = true
	return affected, err
}

// PitcherRecordDeleteOne is the builder for deleting a single PitcherRecord entity.
type PitcherRecordDeleteOne struct {
	prd *PitcherRecordDelete
}

// Where appends a list predicates to the PitcherRecordDelete builder.
func (prdo *PitcherRecordDeleteOne) Where(ps ...predicate.PitcherRecord) *PitcherRecordDeleteOne {
	prdo.prd.mutation.Where(ps...)
	return prdo
}

// Exec executes the deletion query.
func (prdo *PitcherRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := prdo.prd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pitcherrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (prdo *PitcherRecordDeleteOne) ExecX(ctx context.Context) {
	if err := prdo.Exec(ctx); err != nil {
		panic(err)
	}
}
