// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mystats-server/internal/ent/batterrecord"
	"mystats-server/internal/ent/game"
	"mystats-server/internal/ent/pitcherrecord"
	"mystats-server/internal/ent/schema"
	"mystats-server/internal/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	batterrecordFields := schema.BatterRecord{}.Fields()
	_ = batterrecordFields
	// batterrecordDescGames is the schema descriptor for games field.
	batterrecordDescGames := batterrecordFields[0].Descriptor()
	// batterrecord.DefaultGames holds the default value on creation for the games field.
	batterrecord.DefaultGames = batterrecordDescGames.Default.(int)
	// batterrecordDescPlateAppearances is the schema descriptor for plate_appearances field.
	batterrecordDescPlateAppearances := batterrecordFields[2].Descriptor()
	// batterrecord.DefaultPlateAppearances holds the default value on creation for the plate_appearances field.
	batterrecord.DefaultPlateAppearances = batterrecordDescPlateAppearances.Default.(int)
	// batterrecordDescAtBats is the schema descriptor for at_bats field.
	batterrecordDescAtBats := batterrecordFields[3].Descriptor()
	// batterrecord.DefaultAtBats holds the default value on creation for the at_bats field.
	batterrecord.DefaultAtBats = batterrecordDescAtBats.Default.(int)
	// batterrecordDescRuns is the schema descriptor for runs field.
	batterrecordDescRuns := batterrecordFields[4].Descriptor()
	// batterrecord.DefaultRuns holds the default value on creation for the runs field.
	batterrecord.DefaultRuns = batterrecordDescRuns.Default.(int)
	// batterrecordDescHits is the schema descriptor for hits field.
	batterrecordDescHits := batterrecordFields[5].Descriptor()
	// batterrecord.DefaultHits holds the default value on creation for the hits field.
	batterrecord.DefaultHits = batterrecordDescHits.Default.(int)
	// batterrecordDescSingles is the schema descriptor for singles field.
	batterrecordDescSingles := batterrecordFields[6].Descriptor()
	// batterrecord.DefaultSingles holds the default value on creation for the singles field.
	batterrecord.DefaultSingles = batterrecordDescSingles.Default.(int)
	// batterrecordDescDoubles is the schema descriptor for doubles field.
	batterrecordDescDoubles := batterrecordFields[7].Descriptor()
	// batterrecord.DefaultDoubles holds the default value on creation for the doubles field.
	batterrecord.DefaultDoubles = batterrecordDescDoubles.Default.(int)
	// batterrecordDescTriples is the schema descriptor for triples field.
	batterrecordDescTriples := batterrecordFields[8].Descriptor()
	// batterrecord.DefaultTriples holds the default value on creation for the triples field.
	batterrecord.DefaultTriples = batterrecordDescTriples.Default.(int)
	// batterrecordDescHomeruns is the schema descriptor for homeruns field.
	batterrecordDescHomeruns := batterrecordFields[9].Descriptor()
	// batterrecord.DefaultHomeruns holds the default value on creation for the homeruns field.
	batterrecord.DefaultHomeruns = batterrecordDescHomeruns.Default.(int)
	// batterrecordDescWalks is the schema descriptor for walks field.
	batterrecordDescWalks := batterrecordFields[10].Descriptor()
	// batterrecord.DefaultWalks holds the default value on creation for the walks field.
	batterrecord.DefaultWalks = batterrecordDescWalks.Default.(int)
	// batterrecordDescRbis is the schema descriptor for rbis field.
	batterrecordDescRbis := batterrecordFields[11].Descriptor()
	// batterrecord.DefaultRbis holds the default value on creation for the rbis field.
	batterrecord.DefaultRbis = batterrecordDescRbis.Default.(int)
	// batterrecordDescSteals is the schema descriptor for steals field.
	batterrecordDescSteals := batterrecordFields[12].Descriptor()
	// batterrecord.DefaultSteals holds the default value on creation for the steals field.
	batterrecord.DefaultSteals = batterrecordDescSteals.Default.(int)
	// batterrecordDescHitByPitch is the schema descriptor for hit_by_pitch field.
	batterrecordDescHitByPitch := batterrecordFields[13].Descriptor()
	// batterrecord.DefaultHitByPitch holds the default value on creation for the hit_by_pitch field.
	batterrecord.DefaultHitByPitch = batterrecordDescHitByPitch.Default.(int)
	// batterrecordDescStrikeouts is the schema descriptor for strikeouts field.
	batterrecordDescStrikeouts := batterrecordFields[14].Descriptor()
	// batterrecord.DefaultStrikeouts holds the default value on creation for the strikeouts field.
	batterrecord.DefaultStrikeouts = batterrecordDescStrikeouts.Default.(int)
	// batterrecordDescDoublePlays is the schema descriptor for double_plays field.
	batterrecordDescDoublePlays := batterrecordFields[15].Descriptor()
	// batterrecord.DefaultDoublePlays holds the default value on creation for the double_plays field.
	batterrecord.DefaultDoublePlays = batterrecordDescDoublePlays.Default.(int)
	// batterrecordDescCreatedAt is the schema descriptor for created_at field.
	batterrecordDescCreatedAt := batterrecordFields[20].Descriptor()
	// batterrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	batterrecord.DefaultCreatedAt = batterrecordDescCreatedAt.Default.(func() time.Time)
	// batterrecordDescUpdatedAt is the schema descriptor for updated_at field.
	batterrecordDescUpdatedAt := batterrecordFields[21].Descriptor()
	// batterrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	batterrecord.DefaultUpdatedAt = batterrecordDescUpdatedAt.Default.(func() time.Time)
	// batterrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	batterrecord.UpdateDefaultUpdatedAt = batterrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescCreatedAt is the schema descriptor for created_at field.
	gameDescCreatedAt := gameFields[6].Descriptor()
	// game.DefaultCreatedAt holds the default value on creation for the created_at field.
	game.DefaultCreatedAt = gameDescCreatedAt.Default.(func() time.Time)
	// gameDescUpdatedAt is the schema descriptor for updated_at field.
	gameDescUpdatedAt := gameFields[7].Descriptor()
	// game.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	game.DefaultUpdatedAt = gameDescUpdatedAt.Default.(func() time.Time)
	// game.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	game.UpdateDefaultUpdatedAt = gameDescUpdatedAt.UpdateDefault.(func() time.Time)
	pitcherrecordFields := schema.PitcherRecord{}.Fields()
	_ = pitcherrecordFields
	// pitcherrecordDescGames is the schema descriptor for games field.
	pitcherrecordDescGames := pitcherrecordFields[0].Descriptor()
	// pitcherrecord.DefaultGames holds the default value on creation for the games field.
	pitcherrecord.DefaultGames = pitcherrecordDescGames.Default.(int)
	// pitcherrecordDescWins is the schema descriptor for wins field.
	pitcherrecordDescWins := pitcherrecordFields[2].Descriptor()
	// pitcherrecord.DefaultWins holds the default value on creation for the wins field.
	pitcherrecord.DefaultWins = pitcherrecordDescWins.Default.(int)
	// pitcherrecordDescLosses is the schema descriptor for losses field.
	pitcherrecordDescLosses := pitcherrecordFields[3].Descriptor()
	// pitcherrecord.DefaultLosses holds the default value on creation for the losses field.
	pitcherrecord.DefaultLosses = pitcherrecordDescLosses.Default.(int)
	// pitcherrecordDescSaves is the schema descriptor for saves field.
	pitcherrecordDescSaves := pitcherrecordFields[4].Descriptor()
	// pitcherrecord.DefaultSaves holds the default value on creation for the saves field.
	pitcherrecord.DefaultSaves = pitcherrecordDescSaves.Default.(int)
	// pitcherrecordDescHolds is the schema descriptor for holds field.
	pitcherrecordDescHolds := pitcherrecordFields[5].Descriptor()
	// pitcherrecord.DefaultHolds holds the default value on creation for the holds field.
	pitcherrecord.DefaultHolds = pitcherrecordDescHolds.Default.(int)
	// pitcherrecordDescBattersFaced is the schema descriptor for batters_faced field.
	pitcherrecordDescBattersFaced := pitcherrecordFields[7].Descriptor()
	// pitcherrecord.DefaultBattersFaced holds the default value on creation for the batters_faced field.
	pitcherrecord.DefaultBattersFaced = pitcherrecordDescBattersFaced.Default.(int)
	// pitcherrecordDescOpponentAtBats is the schema descriptor for opponent_at_bats field.
	pitcherrecordDescOpponentAtBats := pitcherrecordFields[8].Descriptor()
	// pitcherrecord.DefaultOpponentAtBats holds the default value on creation for the opponent_at_bats field.
	pitcherrecord.DefaultOpponentAtBats = pitcherrecordDescOpponentAtBats.Default.(int)
	// pitcherrecordDescInnings is the schema descriptor for innings field.
	pitcherrecordDescInnings := pitcherrecordFields[9].Descriptor()
	// pitcherrecord.DefaultInnings holds the default value on creation for the innings field.
	pitcherrecord.DefaultInnings = pitcherrecordDescInnings.Default.(float64)
	// pitcherrecordDescHitsAllowed is the schema descriptor for hits_allowed field.
	pitcherrecordDescHitsAllowed := pitcherrecordFields[10].Descriptor()
	// pitcherrecord.DefaultHitsAllowed holds the default value on creation for the hits_allowed field.
	pitcherrecord.DefaultHitsAllowed = pitcherrecordDescHitsAllowed.Default.(int)
	// pitcherrecordDescHomerunsAllowed is the schema descriptor for homeruns_allowed field.
	pitcherrecordDescHomerunsAllowed := pitcherrecordFields[11].Descriptor()
	// pitcherrecord.DefaultHomerunsAllowed holds the default value on creation for the homeruns_allowed field.
	pitcherrecord.DefaultHomerunsAllowed = pitcherrecordDescHomerunsAllowed.Default.(int)
	// pitcherrecordDescWalks is the schema descriptor for walks field.
	pitcherrecordDescWalks := pitcherrecordFields[12].Descriptor()
	// pitcherrecord.DefaultWalks holds the default value on creation for the walks field.
	pitcherrecord.DefaultWalks = pitcherrecordDescWalks.Default.(int)
	// pitcherrecordDescHitByPitch is the schema descriptor for hit_by_pitch field.
	pitcherrecordDescHitByPitch := pitcherrecordFields[13].Descriptor()
	// pitcherrecord.DefaultHitByPitch holds the default value on creation for the hit_by_pitch field.
	pitcherrecord.DefaultHitByPitch = pitcherrecordDescHitByPitch.Default.(int)
	// pitcherrecordDescStrikeouts is the schema descriptor for strikeouts field.
	pitcherrecordDescStrikeouts := pitcherrecordFields[14].Descriptor()
	// pitcherrecord.DefaultStrikeouts holds the default value on creation for the strikeouts field.
	pitcherrecord.DefaultStrikeouts = pitcherrecordDescStrikeouts.Default.(int)
	// pitcherrecordDescEarnedRuns is the schema descriptor for earned_runs field.
	pitcherrecordDescEarnedRuns := pitcherrecordFields[15].Descriptor()
	// pitcherrecord.DefaultEarnedRuns holds the default value on creation for the earned_runs field.
	pitcherrecord.DefaultEarnedRuns = pitcherrecordDescEarnedRuns.Default.(int)
	// pitcherrecordDescCreatedAt is the schema descriptor for created_at field.
	pitcherrecordDescCreatedAt := pitcherrecordFields[19].Descriptor()
	// pitcherrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	pitcherrecord.DefaultCreatedAt = pitcherrecordDescCreatedAt.Default.(func() time.Time)
	// pitcherrecordDescUpdatedAt is the schema descriptor for updated_at field.
	pitcherrecordDescUpdatedAt := pitcherrecordFields[20].Descriptor()
	// pitcherrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pitcherrecord.DefaultUpdatedAt = pitcherrecordDescUpdatedAt.Default.(func() time.Time)
	// pitcherrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pitcherrecord.UpdateDefaultUpdatedAt = pitcherrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
