// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BatterRecord is the predicate function for batterrecord builders.
type BatterRecord func(*sql.Selector)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// PitcherRecord is the predicate function for pitcherrecord builders.
type PitcherRecord func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
